### ISSUE TITLE
Access Denied!  You do not have access to this application.  Please contact your administrator.

### ISSUE THREAD

**Issue by amanfareye** [SAML-Toolkits/java-saml#394]
Hi,
I'm trying to setup the localhost to the onelogin via saml connector. I have done the following, Please help me out where I went wrong:
1. Since the localhost doesn't contain the SSL certificate, So I used the ngrok for https request. 
2. if we try "ngrok URL"/saml/metadata, I get the metdata file and The certificates are valid.
3. I have configured the application and trying to login through the administrator account and it has the access to the app.
4. Still I'm getting "Access Denied" error.
5. Checked the saml tracer but the signature are not getting generated in the request.

Can someone suggest me where i went wrong and why the signature is not present in the request?

**Comment by pitbulk** [comment]
@amanfareye  You need to grant access to the user at the IdP to the application where you registered the java-saml SP metadata.

Right now the logged user has no access, so after authenticate, the IdP is throwing an error indicating that the user has no access to the app.
