### ISSUE TITLE
SAML Response - EncryptionMethod with Algorithm="http://www.w3.org/2009/xmlenc11#rsa-oaep" fails validation

### ISSUE THREAD

**Issue by jinta** [SAML-Toolkits/java-saml#408]
Hi, I'm getting SAML Response xsd validation issues if I'm using the below EncryptionMethod for the Assertion. 

Error message:
```
Errors found when validating SAML response with schema: 
[org.xml.sax.SAXParseException; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'xenc11:MGF'.]
```
Extract of the saml response:
```xml
...
<xenc:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#rsa-oaep">
    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
    <xenc11:MGF xmlns:null="http://www.w3.org/2009/xmlenc11#" xmlns:xenc11="http://www.w3.org/2009/xmlenc11#" Algorithm="http://www.w3.org/2009/xmlenc11#mgf1sha256"/>
</xenc:EncryptionMethod>
...
```
A bit surprised if it turns out that it isn't fully supported which is why I'm raising this issue.

I'm not finding anything obvious that would indicate that "http://www.w3.org/2009/xmlenc11#rsa-oaep" **is or isn't** fully supported.  But after going through the xsd's I'm leaning towards no and it's supposed to use **xmlenc#rsa-oaep-mgf1p** instead of **xmlenc11#rsa-oaep**. 

Would that be correct?

Note: I'm using java-saml v.2.4.0

**Comment by pitbulk** [comment]
java-saml uses [xmlsec](https://santuario.apache.org/) to handle the sign/validation/encrypt/decrypt.

You are right, you may use rsa-oaep-mgf1p and not rsa-oaep
